import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MoreHorizontal, Pencil, Plus, ShieldCheck, Trash2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { EmptyRows, ErrorPanel, fieldClass, labelClass, LoadingRows, PageHeading, Pagination, SearchBox, Toggle } from '@/components/identity-ui'
import { apiClient } from '@/lib/api/api-client'
import type { ApiModels } from '@/lib/api/endpoints'
import { isGranted } from '@/lib/auth/permissions'

type Role = ApiModels['Volo.Abp.Identity.IdentityRoleDto']
const PAGE_SIZE = 10
const message = (error: unknown) => (error as { response?: { data?: { error?: { message?: string } } }; message?: string })?.response?.data?.error?.message ?? (error as Error)?.message ?? 'An unexpected error occurred.'

export function RolesPage() {
  const qc = useQueryClient(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [page, setPage] = useState(0)
  const [current, setCurrent] = useState<Role | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [isDefault, setDefault] = useState(false); const [isPublic, setPublic] = useState(true); const [deleting, setDeleting] = useState<Role | null>(null); const [menu, setMenu] = useState<string | null>(null)
  useEffect(() => { const timer = setTimeout(() => { setFilter(search); setPage(0) }, 300); return () => clearTimeout(timer) }, [search])
  const roles = useQuery({ queryKey: ['roles', filter, page], queryFn: () => apiClient.getIdentityRoles({ query: { Filter: filter || undefined, SkipCount: page * PAGE_SIZE, MaxResultCount: PAGE_SIZE, Sorting: 'name' } }) })
  const save = useMutation({ mutationFn: () => current?.id ? apiClient.putIdentityRolesId({ path: { id: current.id }, body: { name: name.trim(), isDefault, isPublic, concurrencyStamp: current.concurrencyStamp } }) : apiClient.postIdentityRoles({ body: { name: name.trim(), isDefault, isPublic } }), onSuccess: () => { toast.success(current ? 'Role updated successfully.' : 'Role created successfully.'); setOpen(false); void qc.invalidateQueries({ queryKey: ['roles'] }); void qc.invalidateQueries({ queryKey: ['assignable-roles'] }) }, onError: (e) => toast.error(message(e)) })
  const remove = useMutation({ mutationFn: (id: string) => apiClient.deleteIdentityRolesId({ path: { id } }), onSuccess: () => { toast.success('Role deleted successfully.'); setDeleting(null); void qc.invalidateQueries({ queryKey: ['roles'] }) }, onError: (e) => toast.error(message(e)) })
  const create = () => { setCurrent(null); setName(''); setDefault(false); setPublic(true); setOpen(true) }
  const edit = (role: Role) => { setCurrent(role); setName(role.name ?? ''); setDefault(role.isDefault ?? false); setPublic(role.isPublic ?? true); setMenu(null); setOpen(true) }
  const permissions = { create: isGranted('AbpIdentity.Roles.Create'), update: isGranted('AbpIdentity.Roles.Update'), delete: isGranted('AbpIdentity.Roles.Delete') }
  return <div className="space-y-6">
    <PageHeading title="Roles" description="Create roles and manage how they are assigned throughout the application." action={permissions.create ? <Button onClick={create}><Plus className="h-4 w-4" /> New role</Button> : null} />
    {roles.isError && <ErrorPanel message={message(roles.error)} />}
    <Card className="overflow-visible"><div className="flex items-center justify-between gap-4 p-5"><SearchBox value={search} onChange={setSearch} placeholder="Search roles…" /><span className="hidden text-xs text-muted-foreground sm:block">{roles.data?.totalCount ?? 0} roles</span></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-y bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr>{['Actions','Role name','Default','Public'].map((x) => <th key={x} className="px-5 py-3.5 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y">{roles.isLoading ? <LoadingRows columns={4} /> : !roles.data?.items?.length ? <EmptyRows columns={4} message="No roles found." /> : roles.data.items.map((role) => <tr key={role.id} className="hover:bg-muted/30"><td className="relative px-5 py-3"><Button variant="outline" size="sm" onClick={() => setMenu(menu === role.id ? null : role.id!)}>Actions <MoreHorizontal className="h-4 w-4" /></Button>{menu === role.id && <div className="absolute left-5 top-12 z-20 w-36 rounded-lg border bg-card p-1 shadow-xl">{permissions.update && <button className="flex w-full items-center gap-2 rounded-md px-3 py-2 hover:bg-muted" onClick={() => edit(role)}><Pencil className="h-4 w-4" /> Edit</button>}{permissions.delete && !role.isStatic && <button className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-destructive hover:bg-muted" onClick={() => { setDeleting(role); setMenu(null) }}><Trash2 className="h-4 w-4" /> Delete</button>}</div>}</td><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><ShieldCheck className="h-4 w-4" /></span><b>{role.name}</b>{role.isStatic && <span className="rounded bg-muted px-2 py-0.5 text-[10px] font-semibold uppercase text-muted-foreground">Static</span>}</div></td><td className="px-5 py-3"><span className={role.isDefault ? 'text-emerald-600' : 'text-muted-foreground'}>{role.isDefault ? 'Yes' : 'No'}</span></td><td className="px-5 py-3"><span className={role.isPublic ? 'text-emerald-600' : 'text-muted-foreground'}>{role.isPublic ? 'Yes' : 'No'}</span></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={PAGE_SIZE} total={roles.data?.totalCount ?? 0} onPage={setPage} /></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{current ? 'Edit role' : 'New role'}</DialogTitle><DialogDescription>{current ? 'Update role information.' : 'Create a role that can be assigned to users.'}</DialogDescription></DialogHeader><form className="mt-5 space-y-5" onSubmit={(e: FormEvent) => { e.preventDefault(); save.mutate() }}><label className={fieldClass}><span className={labelClass}>Role name *</span><Input required autoFocus value={name} onChange={(e) => setName(e.target.value)} /></label><div className="space-y-3"><Toggle checked={isDefault} onChange={setDefault} label="Default role" /><Toggle checked={isPublic} onChange={setPublic} label="Public role" /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save'}</Button></div></form></DialogContent></Dialog>
    <Dialog open={Boolean(deleting)} onOpenChange={(v) => !v && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Delete role</DialogTitle><DialogDescription>Are you sure you want to delete <b>{deleting?.name}</b>? This action cannot be undone.</DialogDescription></DialogHeader><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setDeleting(null)}>Cancel</Button><Button variant="destructive" disabled={remove.isPending} onClick={() => deleting?.id && remove.mutate(deleting.id)}>{remove.isPending ? 'Deleting…' : 'Delete'}</Button></div></DialogContent></Dialog>
  </div>
}
