import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MoreHorizontal, Pencil, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { EmptyRows, ErrorPanel, fieldClass, labelClass, LoadingRows, PageHeading, Pagination, SearchBox, Toggle } from '@/components/identity-ui'
import { apiClient } from '@/lib/api/api-client'
import type { ApiModels } from '@/lib/api/endpoints'
import { isGranted } from '@/lib/auth/permissions'

type User = ApiModels['Volo.Abp.Identity.IdentityUserDto']
type Role = ApiModels['Volo.Abp.Identity.IdentityRoleDto']
type Form = { userName: string; name: string; surname: string; email: string; phoneNumber: string; password: string; isActive: boolean; lockoutEnabled: boolean; roleNames: string[] }
const blank: Form = { userName: '', name: '', surname: '', email: '', phoneNumber: '', password: '', isActive: true, lockoutEnabled: true, roleNames: [] }
const PAGE_SIZE = 10
const message = (error: unknown) => (error as { response?: { data?: { error?: { message?: string } } }; message?: string })?.response?.data?.error?.message ?? (error as Error)?.message ?? 'An unexpected error occurred.'

export function UsersPage() {
  const qc = useQueryClient(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [page, setPage] = useState(0)
  const [current, setCurrent] = useState<User | null>(null); const [form, setForm] = useState<Form>(blank); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<User | null>(null); const [menu, setMenu] = useState<string | null>(null)
  useEffect(() => { const timer = setTimeout(() => { setFilter(search); setPage(0) }, 300); return () => clearTimeout(timer) }, [search])
  const users = useQuery({ queryKey: ['users', filter, page], queryFn: () => apiClient.getIdentityUsers({ query: { Filter: filter || undefined, SkipCount: page * PAGE_SIZE, MaxResultCount: PAGE_SIZE, Sorting: 'userName' } }) })
  const roles = useQuery({ queryKey: ['assignable-roles'], queryFn: () => apiClient.getIdentityUsersAssignableRoles() })
  const selectedRoles = useQuery({ queryKey: ['user-roles', current?.id], enabled: Boolean(open && current?.id), queryFn: () => apiClient.getIdentityUsersIdRoles({ path: { id: current!.id! } }) })
  useEffect(() => { if (selectedRoles.data?.items) setForm((old) => ({ ...old, roleNames: selectedRoles.data.items!.flatMap((role) => role.name ? [role.name] : []) })) }, [selectedRoles.data])
  const save = useMutation({ mutationFn: () => { const body = { userName: form.userName.trim(), name: form.name.trim() || null, surname: form.surname.trim() || null, email: form.email.trim(), phoneNumber: form.phoneNumber.trim() || null, isActive: form.isActive, lockoutEnabled: form.lockoutEnabled, roleNames: form.roleNames }; return current?.id ? apiClient.putIdentityUsersId({ path: { id: current.id }, body: { ...body, password: form.password || null, concurrencyStamp: current.concurrencyStamp } }) : apiClient.postIdentityUsers({ body: { ...body, password: form.password } }) }, onSuccess: () => { toast.success(current ? 'User updated successfully.' : 'User created successfully.'); setOpen(false); void qc.invalidateQueries({ queryKey: ['users'] }) }, onError: (e) => toast.error(message(e)) })
  const remove = useMutation({ mutationFn: (id: string) => apiClient.deleteIdentityUsersId({ path: { id } }), onSuccess: () => { toast.success('User deleted successfully.'); setDeleting(null); void qc.invalidateQueries({ queryKey: ['users'] }) }, onError: (e) => toast.error(message(e)) })
  const create = () => { setCurrent(null); setForm(blank); setOpen(true) }
  const edit = (user: User) => { setCurrent(user); setForm({ userName: user.userName ?? '', name: user.name ?? '', surname: user.surname ?? '', email: user.email ?? '', phoneNumber: user.phoneNumber ?? '', password: '', isActive: user.isActive ?? true, lockoutEnabled: user.lockoutEnabled ?? true, roleNames: [] }); setMenu(null); setOpen(true) }
  const permissions = { create: isGranted('AbpIdentity.Users.Create'), update: isGranted('AbpIdentity.Users.Update'), delete: isGranted('AbpIdentity.Users.Delete') }
  return <div className="space-y-6">
    <PageHeading title="Users" description="Manage user accounts, profile information, status and assigned roles." action={permissions.create ? <Button onClick={create}><Plus className="h-4 w-4" /> New user</Button> : null} />
    {users.isError && <ErrorPanel message={message(users.error)} />}
    <Card className="overflow-visible"><div className="flex items-center justify-between gap-4 p-5"><SearchBox value={search} onChange={setSearch} placeholder="Search users…" /><span className="hidden text-xs text-muted-foreground sm:block">{users.data?.totalCount ?? 0} users</span></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-y bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr>{['Actions','User name','Name','Email','Phone number','Status'].map((x) => <th key={x} className="px-5 py-3.5 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y">{users.isLoading ? <LoadingRows columns={6} /> : !users.data?.items?.length ? <EmptyRows columns={6} message="No users found." /> : users.data.items.map((user) => <tr key={user.id} className="hover:bg-muted/30"><td className="relative px-5 py-3"><Button variant="outline" size="sm" onClick={() => setMenu(menu === user.id ? null : user.id!)}>Actions <MoreHorizontal className="h-4 w-4" /></Button>{menu === user.id && <div className="absolute left-5 top-12 z-20 w-36 rounded-lg border bg-card p-1 shadow-xl">{permissions.update && <button className="flex w-full items-center gap-2 rounded-md px-3 py-2 hover:bg-muted" onClick={() => edit(user)}><Pencil className="h-4 w-4" /> Edit</button>}{permissions.delete && <button className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-destructive hover:bg-muted" onClick={() => { setDeleting(user); setMenu(null) }}><Trash2 className="h-4 w-4" /> Delete</button>}</div>}</td><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-primary/10 font-semibold text-primary">{(user.userName?.[0] ?? 'U').toUpperCase()}</span><b>{user.userName}</b></div></td><td className="px-5 py-3 text-muted-foreground">{[user.name,user.surname].filter(Boolean).join(' ') || '—'}</td><td className="px-5 py-3 text-muted-foreground">{user.email || '—'}</td><td className="px-5 py-3 text-muted-foreground">{user.phoneNumber || '—'}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${user.isActive ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300' : 'bg-muted text-muted-foreground'}`}>{user.isActive ? 'Active' : 'Inactive'}</span></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={PAGE_SIZE} total={users.data?.totalCount ?? 0} onPage={setPage} /></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{current ? 'Edit user' : 'New user'}</DialogTitle><DialogDescription>{current ? `Update ${current.userName}'s account and roles.` : 'Create a new user account and assign roles.'}</DialogDescription></DialogHeader><form onSubmit={(e: FormEvent) => { e.preventDefault(); save.mutate() }} className="mt-5 space-y-6"><div className="grid gap-4 sm:grid-cols-2">{([['User name','userName','text'],['Email','email','email'],['Name','name','text'],['Surname','surname','text'],['Phone number','phoneNumber','tel'],['Password','password','password']] as const).map(([label,key,type]) => <label key={key} className={fieldClass}><span className={labelClass}>{label}{(key === 'userName' || key === 'email' || (key === 'password' && !current)) && ' *'}</span><Input required={key === 'userName' || key === 'email' || (key === 'password' && !current)} type={type} minLength={key === 'password' ? 6 : undefined} autoComplete={key === 'password' ? 'new-password' : undefined} placeholder={key === 'password' && current ? 'Leave blank to keep current' : ''} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}</div><div className="flex gap-6"><Toggle checked={form.isActive} onChange={(isActive) => setForm({...form,isActive})} label="Active" /><Toggle checked={form.lockoutEnabled} onChange={(lockoutEnabled) => setForm({...form,lockoutEnabled})} label="Lockout enabled" /></div><div><h3 className="mb-3 font-semibold">Roles</h3><div className="grid gap-2 rounded-lg border p-4 sm:grid-cols-2">{roles.isLoading || selectedRoles.isLoading ? <span className="text-sm text-muted-foreground">Loading roles…</span> : (roles.data?.items as Role[] | undefined)?.map((role) => <label key={role.id} className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-muted"><input type="checkbox" className="h-4 w-4 accent-primary" checked={Boolean(role.name && form.roleNames.includes(role.name))} onChange={(e) => role.name && setForm({...form,roleNames:e.target.checked ? [...form.roleNames,role.name] : form.roleNames.filter((x) => x !== role.name)})} />{role.name}</label>)}</div></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save'}</Button></div></form></DialogContent></Dialog>
    <Dialog open={Boolean(deleting)} onOpenChange={(v) => !v && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Delete user</DialogTitle><DialogDescription>Are you sure you want to delete <b>{deleting?.userName}</b>? This action cannot be undone.</DialogDescription></DialogHeader><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setDeleting(null)}>Cancel</Button><Button variant="destructive" disabled={remove.isPending} onClick={() => deleting?.id && remove.mutate(deleting.id)}>{remove.isPending ? 'Deleting…' : 'Delete'}</Button></div></DialogContent></Dialog>
  </div>
}
