import { ChevronLeft, ChevronRight, LoaderCircle, Search } from 'lucide-react'
import type { ReactNode } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export const fieldClass = 'space-y-1.5'
export const labelClass = 'text-sm font-medium text-foreground'
export function PageHeading({ title, description, action }: { title: string; description: string; action: ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Identity management</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>{action}</div> }
export function SearchBox({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="pl-9" /></div> }
export function LoadingRows({ columns }: { columns: number }) { return <tr><td colSpan={columns} className="h-56 text-center"><LoaderCircle className="mx-auto h-6 w-6 animate-spin text-primary" /><p className="mt-3 text-sm text-muted-foreground">Loading…</p></td></tr> }
export function EmptyRows({ columns, message }: { columns: number; message: string }) { return <tr><td colSpan={columns} className="h-56 text-center text-sm text-muted-foreground">{message}</td></tr> }
export function Pagination({ page, pageSize, total, onPage }: { page: number; pageSize: number; total: number; onPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="flex flex-col gap-3 border-t border-border/70 px-5 py-4 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="text-muted-foreground">Showing <b className="text-foreground">{total ? page * pageSize + 1 : 0}</b> to <b className="text-foreground">{Math.min(total, (page + 1) * pageSize)}</b> of <b className="text-foreground">{total}</b> entries</span><div className="flex items-center gap-2"><Button variant="outline" size="icon" aria-label="Previous page" disabled={!page} onClick={() => onPage(page - 1)}><ChevronLeft className="h-4 w-4" /></Button><span className="min-w-20 text-center">{page + 1} / {pages}</span><Button variant="outline" size="icon" aria-label="Next page" disabled={page + 1 >= pages} onClick={() => onPage(page + 1)}><ChevronRight className="h-4 w-4" /></Button></div></div> }
export function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (checked: boolean) => void; label: string }) { return <label className="flex cursor-pointer items-center gap-3 text-sm"><button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-6 w-11 rounded-full transition ${checked ? 'bg-primary' : 'bg-slate-300 dark:bg-slate-600'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked ? 'left-6' : 'left-1'}`} /></button>{label}</label> }
export function ErrorPanel({ message }: { message: string }) { return <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-300">{message}</div> }
